name: Label PRs based on target branch

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = await github.rest.repos.getBranch({
             ...context.repo,
            })
            console.log("labels:",branch)
            const issue_number = context.payload.pull_request.number;
            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number,
              labels:["hello"],
            });
        env:
          labels: ${{ steps.check-label.outputs.labels }}
