name: Label PRs based on target branch

on:
  pull_request:
    types: [opened, reopened]

jobs:
  Add-Label-To-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Target Branch
        id: get-target-branch
        run: |
          TARGET_BRANCH=$(echo "${{ github.event.pull_request.base.ref }}")
          LABELS="$TARGET_BRANCH"
         
          echo "labels=$LABELS" >> $GITHUB_OUTPUT
      - name: Add labels to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
           const { labels } = process.env;
            console.log("Target Branch:",labels)
            const issue_number = context.payload.pull_request.number;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: [labels]
            });
        env:
          labels: ${{ steps.get-target-branch.outputs.labels }}
